on:
  pull_request_target:
    branches:
      - main

jobs:
  label-release:
    if: ${{ startsWith(github.event.pull_request.title, 'release:') }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo this is a release PR
      - run: gh pr edit ${{ github.event.pull_request.number }} --add-label release
